Footer
webdev-20/shorti-url-shortener pull request #80
Opened 2022-10-16 00:01 UTC by nancyfontanez

## Summary
Styled footer as mockup.
## Checklist
- [ ] fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] tested locally.
- [x] No error nor warning in the console.

[upload the screenshot here] (optional)
![15 10 2022_19 10 01_REC](https://user-images.githubusercontent.com/100955909/196011821-c4637016-faab-44ce-b446-d1d1b86cac4b.png)

2022-10-16 10:20 UTC, cherylli requested changes
Looks good but a couple of things I noticed are different from the design
- the footer in the design has no gradient
- the footer width is 100% width in the design

2022-10-16 19:34 UTC, nancyfontanez commented
> Looks good but a couple of things I noticed are different from the design
> 
> * the footer in the design has no gradient
Figma's design shows a gradient in the footer. Am I looking at the right one?
![16 10 2022_15 25 19_REC](https://user-images.githubusercontent.com/100955909/196054241-16a04f04-33d1-4bd0-a938-ac8de0972315.png)

> * the footer width is 100% width in the design
I will work on this ASAP.

2022-10-16 22:43 UTC, cherylli commented
yes sorry you're right, there's a gradient. one of my monitors is weird, and I only inspected by eyes

2022-10-17 23:44 UTC, nancyfontanez commented
#80 Footer width fixed.
![15 10 2022_19 10 01_REC](https://user-images.githubusercontent.com/100955909/196303415-c238fcce-8435-47cd-8038-5001f9c9ed17.png)

2022-10-17 23:45 UTC, nancyfontanez commented
> yes sorry you're right, there's a gradient. one of my monitors is weird, and I only inspected by eyes

#80 Footer width fixed.
![17 10 2022_19 41 04_REC](https://user-images.githubusercontent.com/100955909/196303729-6c926175-5553-4031-a09f-7ad1d5fd7e1c.png)

2022-10-18 00:35 UTC, cherylli approved these changes
Looks good!

2022-10-18 07:56 UTC, klezi10 commented on client/src/Components/Footer/Footer.module.css
> +  background: linear-gradient(90deg, rgba(10,14,36,1) 0%, rgba(0,64,87,1) 90%);
Is there a need for the first background property? It gets overridden by the second one anyways?

2022-10-19 06:40 UTC, klezi10 approved these changes

2022-10-19 06:40 UTC, merged